server.port: 8080

#Swagger. Доступен тут: http://localhost:8080/swagger-ui.html
springdoc:
  swagger-ui:
    try-it-out-enabled: true #Чтобы кнопка 'Try it out' была включена по умолчанию

spring:
  output.ansi.enabled: ALWAYS
  application.name: spring-autotestgenerator
